/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import controller.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Admin
 */
public class CompetitorInfoFrm extends javax.swing.JFrame {
    private boolean isFriend;
    private User user;
    /**
     * Creates new form CompetitorInfoFrm
     */
    public CompetitorInfoFrm(User user) {
        try {
            initComponents();
            this.user = user;
            this.setTitle("Caro Game Nhóm 5");
            this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
            this.setResizable(false);
            this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            this.setLocationRelativeTo(null);
            lbl_avatar.setIcon(new ImageIcon("assets/game/"+user.getAvatar()+".gif"));
            lbl_nickname1.setText(user.getNickname());
            lbl_sovanchoi1.setText(""+user.getNumberOfGame());
            lbl_sovanthang1.setText(""+user.getNumberOfWin());
            lbl_sovanhoa1.setText(""+user.getNumberOfDraw());
            lbl_thuhang1.setText(""+user.getRank());
            if(user.getNumberOfGame()==0){
                lbl_tilethang1.setText("-");
            }
            else{
                lbl_tilethang1.setText(String.format("%.2f",(float)user.getNumberOfWin()/user.getNumberOfGame()*100)+"%");
            }
            lbl_diem1.setText(""+(user.getNumberOfWin()*10+user.getNumberOfGame()));
            Client.socketHandle.write("check-friend,"+user.getID());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    public void checkFriend(boolean isFriend){
        this.isFriend = isFriend;
        if(isFriend){
            btn_themban.setIcon(new ImageIcon("assets/icon/friendship.png"));
            btn_themban.setToolTipText("Bạn bè");
            lbl_danglabanbe.setText("Bạn bè");
            
        }
        else{
            btn_themban.setIcon(new ImageIcon("assets/icon/add-friend.png"));
            btn_themban.setToolTipText("Click để gửi yêu cầu kết bạn");
            lbl_danglabanbe.setText("Kết bạn để chơi cùng nhau dễ dàng hơn");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_thongtindoithu = new javax.swing.JLabel();
        btn_themban = new javax.swing.JButton();
        btn_themban.setFont(new Font("Tahoma", Font.BOLD, 18));
        btn_themban.setText("Thêm");
        lbl_nickname = new javax.swing.JLabel();
        lbl_sovanchoi = new javax.swing.JLabel();
        lbl_sovanthang = new javax.swing.JLabel();
        lbl_danglabanbe = new javax.swing.JLabel();
        lbl_avatar = new javax.swing.JLabel();
        lbl_nickname1 = new javax.swing.JLabel();
        lbl_sovanchoi1 = new javax.swing.JLabel();
        lbl_sovanthang1 = new javax.swing.JLabel();
        lbl_diem = new javax.swing.JLabel();
        lbl_thuhang = new javax.swing.JLabel();
        lbl_diem1 = new javax.swing.JLabel();
        lbl_thuhang1 = new javax.swing.JLabel();
        lbl_tilethang = new javax.swing.JLabel();
        lbl_tilethang1 = new javax.swing.JLabel();
        lbl_sovanhoa = new javax.swing.JLabel();
        lbl_sovanhoa1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new Color(0, 128, 0));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        lbl_thongtindoithu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_thongtindoithu.setForeground(new java.awt.Color(255, 255, 255));
        lbl_thongtindoithu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_thongtindoithu.setText("Thông tin đối thủ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_thongtindoithu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lbl_thongtindoithu)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btn_themban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lbl_nickname.setText("Nickname");

        lbl_sovanchoi.setText("Số ván chơi");

        lbl_sovanthang.setText("Số ván thắng");

        lbl_danglabanbe.setForeground(new java.awt.Color(0, 51, 255));
        lbl_danglabanbe.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_danglabanbe.setText("Các bạn hiện đang là bạn bè");

        lbl_nickname1.setText("{nickname}");

        lbl_sovanchoi1.setText("{sovachoi}");

        lbl_sovanthang1.setText("{sovanthang}");

        lbl_diem.setText("Điểm");

        lbl_thuhang.setText("Thứ hạng");

        lbl_diem1.setText("{diem}");

        lbl_thuhang1.setText("{thuhang}");

        lbl_tilethang.setText("Tỉ lệ thắng");

        lbl_tilethang1.setText("{tillethang}");

        lbl_sovanhoa.setText("Số ván hòa");

        lbl_sovanhoa1.setText("{sovanhoa}");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lbl_danglabanbe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sovanchoi, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sovanthang, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lbl_nickname, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(33, 33, 33))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lbl_tilethang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl_thuhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                            .addGap(35, 35, 35)))
                    .addComponent(lbl_diem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sovanhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl_sovanthang1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(lbl_sovanchoi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btn_themban, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbl_tilethang1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lbl_thuhang1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_diem1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_nickname1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_sovanhoa1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_avatar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_themban, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nickname)
                    .addComponent(lbl_nickname1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sovanchoi)
                    .addComponent(lbl_sovanchoi1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sovanthang)
                    .addComponent(lbl_sovanthang1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_sovanhoa)
                    .addComponent(lbl_sovanhoa1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tilethang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_diem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_thuhang))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbl_tilethang1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_diem1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_thuhang1)))
                .addGap(18, 18, 18)
                .addComponent(lbl_danglabanbe)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(isFriend){
            JOptionPane.showMessageDialog(rootPane, "Bạn và đối thủ đang là bạn bè");
        }
        else{
            int res = JOptionPane.showConfirmDialog(rootPane, "Bạn đồng ý gửi lời mời kết bạn tới đối thủ chứ", "Xác nhận yêu cầu kết bạn", JOptionPane.YES_NO_OPTION);
            if(res==JOptionPane.YES_OPTION){
                try {
                    Client.socketHandle.write("make-friend,"+user.getID());
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_themban;
    private javax.swing.JLabel lbl_thongtindoithu;
    private javax.swing.JLabel lbl_diem;
    private javax.swing.JLabel lbl_thuhang;
    private javax.swing.JLabel lbl_diem1;
    private javax.swing.JLabel lbl_thuhang1;
    private javax.swing.JLabel lbl_tilethang;
    private javax.swing.JLabel lbl_tilethang1;
    private javax.swing.JLabel lbl_sovanhoa;
    private javax.swing.JLabel lbl_sovanhoa1;
    private javax.swing.JLabel lbl_nickname;
    private javax.swing.JLabel lbl_sovanchoi;
    private javax.swing.JLabel lbl_sovanthang;
    private javax.swing.JLabel lbl_danglabanbe;
    private javax.swing.JLabel lbl_avatar;
    private javax.swing.JLabel lbl_nickname1;
    private javax.swing.JLabel lbl_sovanchoi1;
    private javax.swing.JLabel lbl_sovanthang1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
