package view;
import controller.Client;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import model.User;
import java.awt.Color;


public class RankFrm extends javax.swing.JFrame {
    private DefaultTableModel tableModel;
    private List<User> listUserStatics;
    private List<String> rankSrc;
    /**
     * Creates new form RankFrm
     */
    public RankFrm() {
        initComponents();
        this.setTitle("Caro Game Nhóm 2 Diện nè");
        tableModel = (DefaultTableModel) jTable_rank.getModel();
        this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
        this.setResizable(false);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
        rankSrc = new ArrayList<>();
        rankSrc.add("rank-gold");
        rankSrc.add("rank-sliver");
        rankSrc.add("bronze-rank");
        for(int i=0; i<5; i++){
            rankSrc.add("nomal-rank");
        }
        try {
            Client.socketHandle.write("get-rank-charts,");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }
    
    public void setDataToTable(List<User> users){
        this.listUserStatics = users;
        tableModel.setRowCount(0);
        int i=0;
        for(User user : listUserStatics){
            tableModel.addRow(new Object[]{
                i+1,
                user.getNickname(),
                new ImageIcon("assets/icon/"+rankSrc.get(i)+".png")
            });
            i++;
        }

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_rank = new javax.swing.JPanel();
        lbl_rank = new javax.swing.JLabel();
        jScrollPane_rank = new javax.swing.JScrollPane();
        Object[][] rows = {
        };
        String[] columns = {"Nickname","Điểm","Rank"};
        DefaultTableModel model = new DefaultTableModel(rows, columns){
            @Override
            public Class<?> getColumnClass(int column){
                switch(column){
                    case 0: return String.class;
                    case 1: return String.class;
                    case 2: return ImageIcon.class;
                    default: return Object.class;
                }
            }
        };
        jTable_rank = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        panel_rank.setBackground(new Color(0, 128, 0));

        lbl_rank.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_rank.setForeground(new java.awt.Color(255, 255, 255));
        lbl_rank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rank.setText("Bảng xếp hạng");

        jTable_rank.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable_rank.setModel(model);
        jTable_rank.setFillsViewportHeight(true);
        jTable_rank.setRowHeight(62);
        jTable_rank.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	jTable_rankMouseClicked(evt);
            }
        });
        jScrollPane_rank.setViewportView(jTable_rank);

        javax.swing.GroupLayout gl_panel_rank = new javax.swing.GroupLayout(panel_rank);
        panel_rank.setLayout(gl_panel_rank);
        gl_panel_rank.setHorizontalGroup(
            gl_panel_rank.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_panel_rank.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane_rank, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        gl_panel_rank.setVerticalGroup(
            gl_panel_rank.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panel_rank.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl_rank)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane_rank, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_rank, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_rank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable_rankMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(jTable_rank.getSelectedRow()==-1)
            return;
        if(listUserStatics.get(jTable_rank.getSelectedRow()).getID()==Client.user.getID()){
            JOptionPane.showMessageDialog(rootPane, "Thứ hạng của bạn là "+(jTable_rank.getSelectedRow()+1));
            return;
        }
        Client.openView(Client.View.COMPETITORINFO,listUserStatics.get(jTable_rank.getSelectedRow()));
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl_rank;
    private javax.swing.JPanel panel_rank;
    private javax.swing.JScrollPane jScrollPane_rank;
    private javax.swing.JTable jTable_rank;
    // End of variables declaration//GEN-END:variables
}
