/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Client;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.Color;

/**
 *
 * @author Admin
 */
public class RoomListFrm extends javax.swing.JFrame {
    private Vector<String> listRoom;
    private Vector<String> listPassword;
    private Thread thread;
    private boolean isPlayThread;
    private boolean isFiltered;
    DefaultTableModel defaultTableModel;
    /**
     * Creates new form RoomListFrm
     */
    public RoomListFrm() {
        initComponents();
        this.setTitle("Caro Game Nhóm 2 Diện nè");
        this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        defaultTableModel = (DefaultTableModel) tbl_danhsachphong.getModel();
        isPlayThread = true;
        isFiltered = false;
        thread = new Thread(){
            @Override
            public void run(){
                while (Client.roomListFrm.isDisplayable()&&isPlayThread&&!isFiltered) {                    
                    try {
                        Client.socketHandle.write("view-room-list,");
                        Thread.sleep(500);
                    } catch (IOException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(rootPane, ex.getMessage());
                    }
                }
            }
        };
        thread.start();
    }
    public void updateRoomList(Vector<String> listData, Vector<String> listPassword){
        this.listRoom = listData;
        this.listPassword = listPassword;
        defaultTableModel.setRowCount(0);
        ImageIcon imageIcon;
        for(int i=0; i<listRoom.size(); i++){
            if(listPassword.get(i).equals(" "))
                imageIcon = new ImageIcon("assets/icon/swords-1-mini.png");
            else
                imageIcon = new ImageIcon("assets/icon/swords-1-lock-mini.png");
            defaultTableModel.addRow(new Object[]{
                listRoom.get(i),
                imageIcon
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_danhsachphong = new javax.swing.JPanel();
        lbl_danhsachphong = new javax.swing.JLabel();
        btn_roidanhsachphong = new javax.swing.JButton();
        ScrollPane_danhsachphong = new javax.swing.JScrollPane();
        Object[][] rows = {
        };
        String[] columns = {"Tên phòng",""};
        DefaultTableModel model = new DefaultTableModel(rows, columns){
            @Override
            public Class<?> getColumnClass(int column){
                switch(column){
                    case 0: return String.class;
                    case 1: return ImageIcon.class;
                    default: return Object.class;
                }
            }
        };
        tbl_danhsachphong = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_danhsachphong.setBackground(new Color(0, 128, 0));

        lbl_danhsachphong.setBackground(new java.awt.Color(255, 255, 255));
        lbl_danhsachphong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_danhsachphong.setForeground(new java.awt.Color(255, 255, 255));
        lbl_danhsachphong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_danhsachphong.setText("Danh sách phòng trống");

        btn_roidanhsachphong.setText("X");
        btn_roidanhsachphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btn_roidanhsachphongActionPerformed(evt);
            }
        });

        tbl_danhsachphong.setFont(new java.awt.Font("Tekton Pro", 1, 36)); // NOI18N
        tbl_danhsachphong.setModel(model);
        tbl_danhsachphong.setFillsViewportHeight(true);
        tbl_danhsachphong.setRowHeight(60);
        tbl_danhsachphong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
            	tbl_danhsachphongMouseClicked(evt);
            }
        });
        ScrollPane_danhsachphong.setViewportView(tbl_danhsachphong);
        if (tbl_danhsachphong.getColumnModel().getColumnCount() > 0) {
            tbl_danhsachphong.getColumnModel().getColumn(0).setMinWidth(240);
            tbl_danhsachphong.getColumnModel().getColumn(0).setPreferredWidth(240);
            tbl_danhsachphong.getColumnModel().getColumn(0).setMaxWidth(240);
            tbl_danhsachphong.getColumnModel().getColumn(1).setMinWidth(120);
            tbl_danhsachphong.getColumnModel().getColumn(1).setPreferredWidth(120);
            tbl_danhsachphong.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        javax.swing.GroupLayout gl_panel_danhsachphong = new javax.swing.GroupLayout(panel_danhsachphong);
        panel_danhsachphong.setLayout(gl_panel_danhsachphong);
        gl_panel_danhsachphong.setHorizontalGroup(
            gl_panel_danhsachphong.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panel_danhsachphong.createSequentialGroup()
                .addComponent(btn_roidanhsachphong)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(lbl_danhsachphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(gl_panel_danhsachphong.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPane_danhsachphong, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gl_panel_danhsachphong.setVerticalGroup(
            gl_panel_danhsachphong.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panel_danhsachphong.createSequentialGroup()
                .addComponent(btn_roidanhsachphong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_danhsachphong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(ScrollPane_danhsachphong, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_danhsachphong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_danhsachphong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_roidanhsachphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Client.closeView(Client.View.ROOMLIST);
        Client.openView(Client.View.HOMEPAGE);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_danhsachphongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(tbl_danhsachphong.getSelectedRow()==-1){      
        }else{
            try {
                isPlayThread = false;
                int index = tbl_danhsachphong.getSelectedRow();
                int room = Integer.parseInt(listRoom.get(index).split(" ")[1]);
                String password = listPassword.get(index);
                if(password.equals(" ")){
                    Client.socketHandle.write("join-room,"+room);
                    Client.closeView(Client.View.ROOMLIST);
                }
                else{
                    Client.closeView(Client.View.ROOMLIST);
                    Client.openView(Client.View.JOINROOMPASSWORD, room, password);
                }
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage());
            }
        }
    }//GEN-LAST:event_jTable1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_roidanhsachphong;
    private javax.swing.JLabel lbl_danhsachphong;
    private javax.swing.JPanel panel_danhsachphong;
    private javax.swing.JScrollPane ScrollPane_danhsachphong;
    private javax.swing.JTable tbl_danhsachphong;
    // End of variables declaration//GEN-END:variables
}
