/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Client;
import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;

/**
 *
 * @author Admin
 */
public class WaitingRoomFrm extends javax.swing.JFrame {
    private boolean isOpenning;
    /**
     * Creates new form WaitingRoomFrm
     */
    public WaitingRoomFrm() {
        initComponents();
        this.setTitle("Caro Game Nhóm 2 Diện nè");
        isOpenning = false;
        this.setIconImage(new ImageIcon("assets/image/caroicon.png").getImage());
        this.setResizable(false);
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);
        this.setLocationRelativeTo(null);
        lbl_iconloading.setIcon(new ImageIcon("assets/icon/loading2.gif"));
        btn_roikhoiphong.setIcon(new ImageIcon("assets/icon/door_exit.png"));
        lbl_matkhau.setVisible(false);
    }
    public void setRoomName(String roomName){
        lbl_phong.setText("Phòng "+roomName);
    }
    
    public void setRoomPassword(String password){
        lbl_matkhau.setText(password);
        lbl_matkhau.setVisible(true);
    }
    
    public void showFindedCompetitor(){
        isOpenning = true;
        lbl_dangchonguoichoikhac.setText("Đã tìm thấy đối thủ, đang vào phòng");
        lbl_dangchonguoichoikhac.setForeground(Color.BLUE);
        btn_roikhoiphong.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_phong = new javax.swing.JPanel();
        lbl_phong = new javax.swing.JLabel();
        lbl_matkhau = new javax.swing.JLabel();
        lbl_dangchonguoichoikhac = new javax.swing.JLabel();
        lbl_iconloading = new javax.swing.JLabel();
        btn_roikhoiphong = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_phong.setBackground(new Color(0, 128, 0));

        lbl_phong.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_phong.setForeground(new java.awt.Color(255, 255, 255));
        lbl_phong.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_phong.setText("Phòng {}");

        lbl_matkhau.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_matkhau.setForeground(new java.awt.Color(255, 255, 255));
        lbl_matkhau.setText("Mật khẩu:");

        javax.swing.GroupLayout gl_panel_phong = new javax.swing.GroupLayout(panel_phong);
        panel_phong.setLayout(gl_panel_phong);
        gl_panel_phong.setHorizontalGroup(
            gl_panel_phong.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_phong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gl_panel_phong.createSequentialGroup()
                .addContainerGap(210, Short.MAX_VALUE)
                .addComponent(lbl_matkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        gl_panel_phong.setVerticalGroup(
            gl_panel_phong.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gl_panel_phong.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lbl_phong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_matkhau)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_dangchonguoichoikhac.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        lbl_dangchonguoichoikhac.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_dangchonguoichoikhac.setText("Đang chờ người chơi khác vào phòng");

        lbl_iconloading.setText("jLabel3");

        btn_roikhoiphong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	btn_roikhoiphongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_phong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(163, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btn_roikhoiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lbl_iconloading, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
            .addComponent(lbl_dangchonguoichoikhac, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel_phong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_iconloading, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_dangchonguoichoikhac)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_roikhoiphong, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_roikhoiphongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(isOpenning) return;
        try {
            Client.closeView(Client.View.WAITINGROOM);
            Client.openView(Client.View.HOMEPAGE);
            Client.socketHandle.write("cancel-room,");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, ex.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_roikhoiphong;
    private javax.swing.JLabel lbl_phong;
    private javax.swing.JLabel lbl_dangchonguoichoikhac;
    private javax.swing.JLabel lbl_iconloading;
    private javax.swing.JLabel lbl_matkhau;
    private javax.swing.JPanel panel_phong;
    // End of variables declaration//GEN-END:variables
}
